# Generated by Django 2.1.2 on 2018-10-26 00:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181024_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 0, 14, 41, 889356, tzinfo=utc)),
        ),
    ]
