# Generated by Django 2.1.2 on 2018-11-14 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20181114_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 5, 25, 56, 670081, tzinfo=utc)),
        ),
    ]
