# Generated by Django 2.1.2 on 2018-11-14 05:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20181114_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date_entered',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 5, 58, 36, 372643, tzinfo=utc)),
        ),
    ]
