version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: env/bin/python3 immersivetech/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/immersivetech3/immersivetech
    ports:
      - "8000:8000"
    depends_on:
      - db
